### ISSUE TITLE
[Question] transaction usage

### ISSUE THREAD

**Issue by pythoneer** [mehcode/tokio-diesel#12]
I am not quite sure how to use the `transaction` right with tokio-diesel. I am trying to use transactions in my code but wondering if the usage without `execute_async` is correct.

```rust
pub async fn register(
    register_user: Json<WsRegisterUser>,
    db_pool: Data<DbPool>,
) -> Result<HttpResponse, ApiError> {
    use crate::diesel::RunQueryDsl;

    register_user.validate()?;

    FutureRetry::new(
        || {
            let dbn: DbNewUser = register_user.clone().into();

            // db_pool
            //     .get()
            //     .unwrap()
            //     .build_transaction()
            //     .serializable()
            //     .run(|| {
            //          // ...
            //     })

            db_pool.transaction(move |conn| {
                // diesel::insert_into(users)
                //     .values(dbn.clone())
                //     .execute_async(&db_pool)
                //     .await
                diesel::insert_into(users).values(dbn.clone()).execute(conn) //<-- no execute_async
            })
        },
        handle_async_serialize_error,
    )
    .map_err(|(err, _attempts)| err)
    .await?;

    Ok(HttpResponse::Ok().body("register ok"))
}
``` 

The only way to get the code to run was with the "old" `execute` but i am not really sure if this is the right way, because i don't want to block anything by accident. I was previously handling this manually and i wanted to get rid of my code by replacing it with tokio-diesel. But i am not quite sure if i am doing the right thing here without using `.execute_async`. Is  `db_pool.transaction` doing all what is necessary here to run it without blocking?

As a little side question i was previously using transactions with `.build_transaction().serializable()` but i don't think i have access to this anymore with the current version of tokio-diesel, right? So i think i have to enable this on the database configuration level?

**Comment by jgrund** [comment]
Looks like you are using it correctly. It appears the whole thing gets put into a `spawn_blocking` here:

https://github.com/mehcode/tokio-diesel/blob/44577ef5f1ffb79d354093f11d9f57d9c12b176d/src/lib.rs#L128-L133

**Comment by pythoneer** [comment]
@jgrund thanks for pointing this out! I think i can close this now.
