### ISSUE TITLE
Static lifetime is difficult to work with

### ISSUE THREAD

**Issue by jgrund** [mehcode/tokio-diesel#9]
Consider some code like:

```rust
diesel::update(&alert)
    .set((active.eq(Option::<bool>::None), end.eq(diesel::dsl::now)))
    .execute_async(&pool)
    .await;
```

where `alert` is a reference to a struct that implements `Identifiable`.

This code fails with an error like:

```
error[E0597]: `alert` does not live long enough
  --> iml-services/iml-ntp/src/main.rs:47:36
   |
47 |                     diesel::update(&alert)
   |                     ---------------^^^^^^-
   |                     |              |
   |                     |              borrowed value does not live long enough
   |                     argument requires that `alert` is borrowed for `'static`
...
51 |                 }
   |                 - `alert` dropped here while still borrowed
```

I may be missing something obvious but it doesn't seem like it's possible to use non-static references when building a query with this lib.

**Comment by mehcode** [comment]
Sadly it's not possible to remove the static lifetime (as far as I'm aware) as we need to move your query to another thread where the execution happens. 

A database crate built with async (rather than added around it like this) would not have this issue.

**Comment by miquels** [comment]
(just a random drive-by comment)
You could use [`tokio::task::block_in_place`](https://docs.rs/tokio/0.2/tokio/task/fn.block_in_place.html) instead of `task::spawn_blocking`, which does not move the query to another thread. Only works with the (default) threaded runtime, not with the (optional) basic runtime though.

**Comment by mehcode** [comment]
@miquels Very interesting. I didn't know about that. The docs make it sounds like performance is an issue but with everything else going on ( db call, blocking IO ) it might be a wash and would improve the API. Thanks for letting me know.
